"""added game stats

Revision ID: 019f378be543
Revises: 9740624b7ce9
Create Date: 2022-06-12 11:18:51.272660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019f378be543'
down_revision = '9740624b7ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('points_scored', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_stats')
    # ### end Alembic commands ###
