"""Added scenario table

Revision ID: 5b6467490f53
Revises: f1bc68231a78
Create Date: 2022-06-21 16:13:46.804083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6467490f53'
down_revision = 'f1bc68231a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_group_id', sa.String(length=250), nullable=False),
    sa.Column('simulation_id', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    # ### end Alembic commands ###
