"""Added status to playerDb

Revision ID: 64f383182d01
Revises: 1d5e6d54cd8b
Create Date: 2022-07-24 20:18:32.355321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f383182d01'
down_revision = '1d5e6d54cd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('status', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'status')
    # ### end Alembic commands ###
