"""added game_type column

Revision ID: e1a74dbc9a31
Revises: 1008f36aadfc
Create Date: 2021-08-22 10:52:17.500404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a74dbc9a31'
down_revision = '1008f36aadfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_type', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_type')
    # ### end Alembic commands ###
