"""added draft pick stats

Revision ID: 1d5e6d54cd8b
Revises: 5b6467490f53
Create Date: 2022-07-08 15:49:32.266450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5e6d54cd8b'
down_revision = '5b6467490f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_pick_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('points_per_game_mean', sa.Float(), nullable=False),
    sa.Column('points_per_game_std', sa.Float(), nullable=False),
    sa.Column('rebounds_per_game_mean', sa.Float(), nullable=False),
    sa.Column('rebounds_per_game_std', sa.Float(), nullable=False),
    sa.Column('assists_per_game_mean', sa.Float(), nullable=False),
    sa.Column('assists_per_game_std', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vegas_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('odd_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegas_odds')
    op.drop_table('draft_pick_stats')
    # ### end Alembic commands ###
