"""added simulation id to players

Revision ID: 9740624b7ce9
Revises: d731f7e945ff
Create Date: 2022-04-18 20:29:49.798098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9740624b7ce9'
down_revision = 'd731f7e945ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('simulation_id', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'simulation_id')
    # ### end Alembic commands ###
