"""Added age to player

Revision ID: f1bc68231a78
Revises: 019f378be543
Create Date: 2022-06-21 15:35:08.630464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bc68231a78'
down_revision = '019f378be543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'age')
    # ### end Alembic commands ###
