"""added playoff bracket

Revision ID: f9da7d0a70cd
Revises: e1a74dbc9a31
Create Date: 2022-04-18 19:32:13.937664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9da7d0a70cd'
down_revision = 'e1a74dbc9a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoff_brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=250), nullable=True),
    sa.Column('nodes_sep_comma', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playoff_brackets')
    # ### end Alembic commands ###
